### ISSUE TITLE
`carthage build Sync --platform iOS` fails after upgrading to Xcode 9/Swift 4

### ISSUE THREAD

**Issue by tlowrimore** [3lvis/Sync#425]
Hi,

I'm receiving the following error when build Sync, after upgrading to Xcode 9/Swift 4:

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Demo.xcodeproj -scheme Sync-iOS -configuration Release -derivedDataPath /Users/timothylowrimore/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Sync/3.3.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync)
```

It appears the builds for arm7 and arm64 are failing, according to the `xcodebuild` log.  Here's what I'm seeing:

```
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:460:22: error: a non-failable initializer cannot delegate to failable initializer 'init(contentsOf:)' written with 'init?'
                self.init(contentsOf: momdModelURL)
                     ^
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:460:22: note: force potentially-failing result with '!'
                self.init(contentsOf: momdModelURL)
                     ^
                                                   !
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:457:17: note: propagate the failure with 'init?'
    convenience init(bundle: Bundle, name: String) {
                ^
                    ?
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:466:22: error: a non-failable initializer cannot delegate to failable initializer 'init(contentsOf:)' written with 'init?'
                self.init(contentsOf: momModelURL)
                     ^
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:466:22: note: force potentially-failing result with '!'
                self.init(contentsOf: momModelURL)
                     ^
                                                  !
/Users/timothylowrimore/Development/MyProject/Carthage/Checkouts/Sync/Source/DataStack/DataStack.swift:457:17: note: propagate the failure with 'init?'
    convenience init(bundle: Bundle, name: String) {
                ^
                    ?

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
        CompileSwift normal armv7
```

**Comment by 3lvis** [comment]
Hi! Try pointing to master in your Cartfile, will be making a Xcode 9/Swift 4 release later today.

**Comment by 3lvis** [comment]
Check Sync 4 https://github.com/3lvis/Sync/releases/tag/4.0.0

**Comment by tlowrimore** [comment]
Hey Elvis,

Thanks so much for the quick response!

Cheers!

**Comment by Baza207** [comment]
@3lvis Might be good to update the Readme for the Cartage line to `github "3lvis/Sync" ~> 4.0` as 3.0 fails to build in Xcode 9 at the moment (4.0 worked fine once I found this though 😉).

**Comment by 3lvis** [comment]
@Baza207 Thanks James! I'll make the change now.
